# Generated by Django 5.1.3 on 2025-03-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='borrow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
